# Generated by Django 4.1.5 on 2023-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroupassignment',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
    ]
