# Generated by Django 4.1.5 on 2023-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_studentgroupassignment_date_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedGroup',
            fields=[
            ],
            options={
                'verbose_name': 'archived group',
                'verbose_name_plural': 'archived groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('records.studentgroup',),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='archived',
            field=models.BooleanField(default=False, editable=False, verbose_name='Archived'),
        ),
    ]
