# Generated by Django 4.1.5 on 2023-03-26 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_student_teacher_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator('1'), django.core.validators.MaxValueValidator('8')])),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Student Group',
                'verbose_name_plural': 'Student Groups',
                'ordering': ['grade', 'name'],
                'unique_together': {('grade', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(verbose_name='End date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='records.studentgroup', verbose_name='Student group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='records.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Group assignment',
                'verbose_name_plural': 'Group assignments',
            },
        ),
    ]
